In [2]:
from transformers import BertModel, AutoTokenizer

In [3]:
model_name = "bert-base-cased"
model = BertModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [4]:
text = "Tokenize me this please"
encoded_inputs = tokenizer(text, return_tensors = 'pt')
encoded_inputs

{'input_ids': tensor([[ 101, 1706, 6378, 3708, 1143, 1142, 4268,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [6]:
output = model(**encoded_inputs)
output

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 6.3545e-01,  1.7615e-01,  6.1589e-01,  ..., -1.1664e-01,
           5.5535e-01, -2.4577e-01],
         [ 2.6871e-01,  1.0804e-01, -7.9292e-02,  ...,  8.8401e-02,
           8.2027e-01, -7.8524e-04],
         [ 5.9981e-02,  5.7306e-01, -2.6445e-01,  ...,  2.0249e-01,
          -8.9708e-01,  2.3878e-01],
         ...,
         [-1.6705e-01,  3.0571e-01,  4.3537e-01,  ...,  8.0311e-02,
           2.3093e-01,  1.8002e-01],
         [ 4.5541e-01,  1.2220e-01,  5.8000e-01,  ...,  3.0526e-01,
           5.1684e-01, -2.6089e-01],
         [ 7.1147e-01,  3.9667e-02,  3.6133e-01,  ..., -4.8748e-01,
           5.2401e-01, -8.0548e-01]]], grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-0.7571,  0.5197,  0.9999, -0.9967,  0.9707,  0.9701,  0.9926, -0.9949,
         -0.9859, -0.6731,  0.9896,  0.9993, -0.9988, -0.9999,  0.8604, -0.9850,
          0.9931, -0.5585, -1.0000, -0.5781, -0.6435, -0.9999,  0.1552,  0.976

In [7]:
last_hidden_state = output.last_hidden_state
pooler_output = output.pooler_output

In [8]:
last_hidden_state

tensor([[[ 6.3545e-01,  1.7615e-01,  6.1589e-01,  ..., -1.1664e-01,
           5.5535e-01, -2.4577e-01],
         [ 2.6871e-01,  1.0804e-01, -7.9292e-02,  ...,  8.8401e-02,
           8.2027e-01, -7.8524e-04],
         [ 5.9981e-02,  5.7306e-01, -2.6445e-01,  ...,  2.0249e-01,
          -8.9708e-01,  2.3878e-01],
         ...,
         [-1.6705e-01,  3.0571e-01,  4.3537e-01,  ...,  8.0311e-02,
           2.3093e-01,  1.8002e-01],
         [ 4.5541e-01,  1.2220e-01,  5.8000e-01,  ...,  3.0526e-01,
           5.1684e-01, -2.6089e-01],
         [ 7.1147e-01,  3.9667e-02,  3.6133e-01,  ..., -4.8748e-01,
           5.2401e-01, -8.0548e-01]]], grad_fn=<NativeLayerNormBackward0>)

In [9]:
pooler_output

tensor([[-0.7571,  0.5197,  0.9999, -0.9967,  0.9707,  0.9701,  0.9926, -0.9949,
         -0.9859, -0.6731,  0.9896,  0.9993, -0.9988, -0.9999,  0.8604, -0.9850,
          0.9931, -0.5585, -1.0000, -0.5781, -0.6435, -0.9999,  0.1552,  0.9768,
          0.9878,  0.1029,  0.9929,  1.0000,  0.8974, -0.2188,  0.2532, -0.9955,
          0.8232, -0.9994,  0.1654,  0.1601,  0.6032, -0.2848,  0.7803, -0.9705,
         -0.7546, -0.4581,  0.6860, -0.5660,  0.9705,  0.2324,  0.0123,  0.0351,
          0.0350,  0.9999, -0.9770,  0.9985, -0.9960,  0.9980,  0.9982,  0.4647,
          0.9974,  0.1615, -0.9992,  0.3755,  0.9722,  0.2300,  0.9536, -0.2489,
          0.3661, -0.5718, -0.8706,  0.1662, -0.5311,  0.3377,  0.3172,  0.3148,
          0.9917, -0.9334, -0.0862, -0.9375,  0.0015, -0.9999,  0.9716,  1.0000,
          0.7328, -0.9998,  0.9978, -0.2295, -0.7797,  0.6083, -0.9990, -0.9997,
          0.1160, -0.6008,  0.9560, -0.9938,  0.7354, -0.9208,  1.0000, -0.9690,
         -0.1394,  0.4528,  

In [10]:
last_hidden_state.shape

torch.Size([1, 8, 768])

In [11]:
pooler_output.shape

torch.Size([1, 768])

In [12]:
def predict(text):
    encoded_inputs = tokenizer(text, return_tensors = 'pt')
    
    return model(**encoded_inputs)[0]


In [13]:
sentence1 = "There was a fly drinking from my soup"
sentence2 = "To become a commercial pilot, he had to fly for 1500 hrs."

In [15]:
tokens1 = tokenizer.tokenize(sentence1)
tokens2 =  tokenizer.tokenize(sentence2)

In [16]:
tokens1

['There', 'was', 'a', 'fly', 'drinking', 'from', 'my', 'soup']

In [17]:
tokens2

['To',
 'become',
 'a',
 'commercial',
 'pilot',
 ',',
 'he',
 'had',
 'to',
 'fly',
 'for',
 '1500',
 'h',
 '##rs',
 '.']

In [18]:
out1 = predict(sentence1)
out2 = predict(sentence2)


In [19]:
emb1 = out1[0:, tokens1.index("fly"),:].detach()
emb1

tensor([[ 1.3092e-01, -1.0668e-01,  9.2521e-02,  1.3643e-01, -2.0441e-02,
         -4.5883e-01,  2.8127e-01,  6.1601e-02, -3.5428e-01, -2.1475e-01,
         -2.5499e-01,  5.1753e-01, -4.3148e-01, -6.3328e-02, -5.3246e-01,
         -3.2249e-01, -2.1388e-01,  1.3354e-01, -1.9712e-01, -2.6240e-01,
         -1.4709e-01, -1.0367e-01, -2.5171e-01,  5.1877e-01,  9.3922e-02,
         -5.8072e-02, -2.8924e-01,  3.1419e-01, -1.9856e-02,  8.9696e-02,
         -4.5797e-01, -7.0561e-02,  5.0785e-01,  3.4331e-02, -1.3408e-01,
          1.4696e-01,  2.7969e-01,  3.0272e-02,  1.2643e-01, -4.4700e-01,
          2.9013e-01,  4.3904e-02, -2.0638e-01, -1.5396e-01,  2.4499e-01,
         -6.9515e-01,  4.1689e-01, -6.1322e-02, -3.0181e-01, -1.1547e-01,
         -3.1198e-01, -1.6191e-01, -1.8917e-01,  1.5833e-01,  1.3775e-01,
         -3.2496e-01,  2.6430e-01, -1.0327e-01,  2.0264e-01,  6.1191e-01,
         -6.3989e-02,  5.9297e-01,  4.8044e-01,  1.2240e-01, -3.5768e-02,
          2.2697e-01, -2.0584e-01, -2.

In [20]:
emb2 = out2[0:, tokens2.index("fly"),:].detach()
emb2

tensor([[ 3.0121e-01, -3.7453e-01,  1.7246e-01, -2.7174e-01,  3.8028e-01,
          2.0486e-01,  2.1477e-01,  2.8630e-01,  2.8765e-01,  1.9869e-01,
         -3.0768e-02,  5.4414e-01, -2.9874e-01,  2.8696e-01,  3.3922e-02,
         -2.0245e-01,  5.8402e-01,  3.8026e-01, -9.7081e-02,  7.1007e-02,
          2.3671e-01,  7.4407e-01, -1.1773e-01,  5.0391e-01,  2.0671e-01,
         -2.9552e-01,  8.2782e-02, -4.7470e-02,  2.3157e-01,  5.6756e-01,
         -1.2139e-01, -3.1804e-01, -2.4339e-01, -1.3365e-01,  1.1715e-01,
         -2.7521e-01,  1.6187e-01,  6.3206e-02,  6.1370e-01,  7.9106e-02,
          1.7716e-01,  1.2618e-01, -2.6670e-01,  6.5093e-01,  1.3334e-01,
          4.0100e-02, -5.0074e-01,  1.5339e-01,  7.1375e-01, -3.7458e-01,
          1.1029e-01, -2.0244e-01,  6.4233e-02,  4.0867e-01,  1.0986e-01,
          1.9826e-02, -3.3903e-01, -8.0731e-01,  2.3410e-01, -9.4688e-02,
         -3.9465e-01,  7.2130e-02,  1.0747e-01,  4.2151e-01,  6.6764e-01,
          3.6220e-01,  2.6413e-01,  2.

In [24]:
emb1.shape

torch.Size([1, 768])

In [25]:
emb2.shape

torch.Size([1, 768])

In [21]:
# cosine distance betwwen 2 sentences
from scipy.spatial.distance import cosine

In [22]:
cosine(emb1, emb2)

0.4021098017692566